[workspace]
authors = ["Blair-Johnson <blairjohnson@gatech.edu>"]
channels = ["conda-forge"]
name = "TCLM"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.8"

[pypi-dependencies]
torch = "==2.0.0"
numpy = ">=1.24.4, <2"
tqdm = ">=4.67.1, <5"
